name: bright_pig
description: A new Flutter project.

dependencies:
  google_sign_in: "3.0.2"
  #googleapis_auth: any - Not Using
  googleapis: any
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/logo_h.png
   - assets/images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SFPro/SF-Pro-Display-Regular.otf
          style: normal
        - asset: assets/fonts/SFPro/SF-Pro-Display-RegularItalic.otf
          style: italic
  
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
